### ISSUE TITLE
clappr crashes on the first time on ie11

### ISSUE THREAD

**Issue by shacharz** [Peer5/clappr-peer5-playback#3]

**Comment by shacharz** [comment]
@shaharmor this is fixed right?

**Comment by shaharmor** [comment]
No.. It was working on Edge but disn't yet check why it's happening in IE

On Sunday, 25 October 2015, Shachar Zohar notifications@github.com wrote:

> @shaharmor https://github.com/shaharmor this is fixed right?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Peer5/clappr-peer5-playback/issues/3#issuecomment-150899537
> .

## 

## 

Shahar Mor
Software Developer, Peer5
shahar@peer5.com
