### ISSUE TITLE
Status of this plugin?

### ISSUE THREAD

**Issue by bikegriffith** [Peer5/clappr-peer5-playback#4]
It would appear that the plugin you're currently using in production <https://docs.peer5.com/players/clappr/> is entirely different.  Do you have plans to accept contributions on the new one?

I ask because we've found 2 separate issues with the one in production, and I'd love to be able to help fix them if possible:
1. The mechanism used to fetch segments appends data to the URL, breaking systems who use signed URLs for access control
2. The current Clappr hooks appear to work by rewriting the global Clappr object dynamically, rather than by relying on its first-class plugin architecture.  One symptom is that any time I pass in the `options.playback` argument to a new Clappr.Player (e.g. to override some hls.js configuration values), the peer5 plugin fails to work properly.

**Comment by shacharz** [comment]
@bikegriffith Thanks for the feedback.
1. we fixed that, and replied to you directly on intercom
2. plugin have issues on their own, let's followup discussion directly on intercom

**Comment by bikegriffith** [comment]
Thanks for the response! Will check-in on your intercom
